### ISSUE TITLE
Can't install Crispy Forms in Windows

### ISSUE THREAD

**Issue by anfil89** [maraujop/django-crispy-forms#446]
I'm trying to install Crispy Forms in Windows 8.1 and I'm getting the following error:

D:\Dropbox\Django\src>pip install --upgrade django-crispy-forms
Collecting django-crispy-forms
  Downloading django-crispy-forms-1.4.0.tar.gz (47kB)
    100% |################################| 49kB 803kB/s
Building wheels for collected packages: django-crispy-forms
  Running setup.py bdist_wheel for django-crispy-forms
  Stored in directory: C:\Users\Andr\AppData\Local\pip\Cache\wheels\2c\48\36\7c2cb6aab4ab337a344347ba5f7d354736a026700838b80d1e
C:\Python27\lib\urllib.py:1294: UnicodeWarning: Unicode equal comparison failed
to convert both arguments to Unicode - interpreting them as being unequal return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 223, in main status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 293, in run wb.build(autobuilding=True)
  File "C:\Python27\lib\site-packages\pip\wheel.py", line 780, in build path_to_url(wheel_file), trusted=True)
  File "C:\Python27\lib\site-packages\pip\download.py", line 456, in path_to_url url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "C:\Python27\lib\nturl2path.py", line 65, in pathname2url path = path + '/' + urllib.quote(comp)
  File "C:\Python27\lib\urllib.py", line 1294, in quote return ''.join(map(quoter, s))
KeyError: u'\xe9'

Can someone help me?

**Comment by MishY111** [comment]
Try downloading the latest zip and use pip to install that https://github.com/maraujop/django-crispy-forms/archive/dev.zip

**Comment by anfil89** [comment]
Thanks a lot for your reply David, I'll try that :)

**Comment by anfil89** [comment]
Can you tell me what I need to do once I download the crispy forms .zip file?

**Comment by MishY111** [comment]
CD to the dir of your zip file. Then run in a command prompt "pip install XXXX.zip". If that fails use "python pip install XXXX.zip"

**Comment by anfil89** [comment]
I tried that and I got this 
http://i.gyazo.com/d7ac4f67b6acd0cff6c3ba93c4864a8c.png

python pip install filename.zip just throws a command error

**Comment by anfil89** [comment]
Never mind, it was totally my fault... I wasn't able to install Crispy Forms because the "é" in my name (André)... I was getting an unicode error and just now I understand it happened because my Windows user folder name...
Sorry for all the troubble

**Comment by carltongibson** [comment]
Assuming this is fixed. Shout if not.
